language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - node
script:
  - npm run test:prod && npm run build
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run report-coverage'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run deploy-docs'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run semantic-release'
