language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - node
stages:
  - test
  - compile
  - name: deploy
    if: type = push
jobs:
  include:
    - stage: test
      script:
        - npm run test:prod
    - stage: compile
      script:
        - npm run build
    - stage: deploy
      script:
        - npm run report-coverage
        - npm run deploy-docs
        - npm run semantic-release
