language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - node
script:
  - npm run test:prod && npm run build
if: type = push
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
